<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search btn</name>
   <tag></tag>
   <elementGuidId>e9fae6d4-833c-4c4a-b589-456703d830de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#srcTxtbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='srcTxtbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e2ed850-1b2b-47b7-a42b-4171471b91b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b75f3bef-e91b-45a3-99fc-a795bffb8a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryBut  butOuterLine searchbutton</value>
      <webElementGuid>feaef300-e18c-445c-89e2-f90231159821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Jobs</value>
      <webElementGuid>47a7bda5-135f-41bb-bb78-6e9a02b5bff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>srcTxtbtn</value>
      <webElementGuid>dd1709f9-4ce0-4053-8a43-924768e466b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>searchJob()</value>
      <webElementGuid>ddaaa1f2-0185-4dbf-b3e6-efb811ecc982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;srcTxtbtn&quot;)</value>
      <webElementGuid>5bebdc73-fc04-4b75-ac79-2cb2ccc12170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='srcTxtbtn']</value>
      <webElementGuid>abdc4f74-b764-4993-85b3-a0ec8a10e0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>a6aa3dc3-f6a1-451b-a28e-138e7a7e86b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'srcTxtbtn']</value>
      <webElementGuid>16dacdb3-e570-497f-b947-829e709cad64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
