<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_Job</name>
   <tag></tag>
   <elementGuidId>e35dcd11-49f6-45bb-90f6-4c311d2de85c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobtitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobtitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bb0429d-f473-4d6c-bd7e-6bc57d372548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3cbf6bd-1904-4dbe-ac4e-835a006dbff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchCont</value>
      <webElementGuid>b9fd9d58-2fe8-4f4d-9da9-5e4f93c6a506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobtitle</value>
      <webElementGuid>41dc4aba-eb22-4b10-a341-07c062f406d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobtitle</value>
      <webElementGuid>e1c6ed86-1181-4f08-9e3d-571592e8577c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by job title/company name – e.g. accountant, sales director, DTCC</value>
      <webElementGuid>1cfc7cf5-d3fa-4d2e-9a7b-cede36a79f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ac241ee0-a672-40b3-83d2-c7fce599ac26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobtitle&quot;)</value>
      <webElementGuid>d3720be8-3aa9-4102-94a7-52b4197bc65a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobtitle']</value>
      <webElementGuid>09c696a6-552b-4460-8dab-e9415e041cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>5a9eb10b-66aa-4110-9904-e467bd009aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobtitle' and @id = 'jobtitle' and @placeholder = 'Search by job title/company name – e.g. accountant, sales director, DTCC']</value>
      <webElementGuid>6168fd6d-2984-472e-b3a2-699b811d868c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
