<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CONTACT US_btn btn-info</name>
   <tag></tag>
   <elementGuidId>a5bbe1d2-50cf-48f4-b46e-4f5d210fb447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='LOG in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7647eec-ccd1-4e56-bd4d-420658252874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>e73ba394-c1d3-43b5-a8d0-01b4c9719a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8735dd60-941c-436b-82aa-e1d6ce737a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LOG in</value>
      <webElementGuid>0ae6e114-0415-4de4-b078-10e9c30e7533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-collapse&quot;)/ul[@class=&quot;nav navbar-nav navbar-with-inside clearfix navbar-right with-border&quot;]/li[@class=&quot;hidden-xs hidden-sm&quot;]/a[1]/input[@class=&quot;btn btn-info&quot;]</value>
      <webElementGuid>2a578b6e-4fb7-4f2d-a2e6-e4599b0418d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='LOG in']</value>
      <webElementGuid>fff58026-4f4d-465e-958c-a204c19ebdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-collapse']/ul/li[8]/a/input</value>
      <webElementGuid>b4675a2f-3d3d-4b39-8900-46fc83369556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d3a5a08-a05e-462c-9265-638a72e23427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>c90d6ae0-1f98-46da-8158-2009d0d00764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
