<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_LG-btn</name>
   <tag></tag>
   <elementGuidId>75d89a31-e3c9-4b0f-822a-a1f53ebd1699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.LG-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Log in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4872e85c-7b43-478b-936a-a1058a97308b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LG-btn</value>
      <webElementGuid>e442a532-271f-44c9-9e0b-f1499ae910a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e5f70d4-5ffb-4003-b59a-469d8fb73d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>affce8f3-bfbe-470e-8ab5-e05cb40d83f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[1]/form[@class=&quot;ng-pristine ng-valid ng-touched&quot;]/div[@class=&quot;LG-bgcontainer&quot;]/div[@class=&quot;LG-form-section&quot;]/input[@class=&quot;LG-btn&quot;]</value>
      <webElementGuid>4effad46-1fef-4226-8c85-6eb7ef10483d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Log in']</value>
      <webElementGuid>2f7cba42-032a-4c4c-aa34-913cd85e747a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2b71fdc9-ebcd-43c6-846c-b2649cca692b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>1009d9d7-1640-4a94-bfbc-98888b2a74e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
